name: Automation

on:
  issues:
    types:
    - labeled

jobs:
  issues:
    runs-on: ubuntu-latest
    name: Issue Automation
    steps:
    - name: Debug Info
      env:
        EVENT: ${{ toJSON(github.event) }}
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "${EVENT}"
        jq -h
