name: Automation

on:
  issues:
    types:
    - labeled

jobs:
  issues:
    runs-on: ubuntu-latest
    name: Issue Automation
    steps:
    - name: Debug Info
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "${{ toJSON(github.event) }}"
        jq -h
