name: Documentation
on:
  pull_request:
    branches:
    - release
    - develop
    - beta
    paths:
    - 'docs/**'
    - 'lib/esbonio/**'
    - 'lib/esbonio-extensions/**'
  push:
    branches:
    - release
    - beta
    - develop
    paths:
    - 'docs/**'
    - 'lib/esbonio/**'
    - 'lib/esbonio-extensions/**'

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - run: |
        set -e

        python --version
        python -m pip install --upgrade pip
        python -m pip install -r docs/requirements.txt

      name: Setup Environment

    - id: build
      run: |
        set -e

        cd docs
        make html
      name: Build Docs

    - name: 'Upload Aritfact'
      uses: actions/upload-artifact@v3
      with:
        name: 'docs'
        path: 'docs/_build/${{ steps.build.outputs.version }}'
